### ISSUE TITLE
cant get client name or mods. getting null insted of names

### ISSUE THREAD

**Issue by Nilesh3803** [Fritcha/Client-Detector#2]
![image](https://github.com/Fritcha/Client-Detector/assets/86995974/8ddcdfe2-cd8f-4c26-9e86-c5623774987b)
y i am getting null insted of vanila or optifine. 

Edit: i cant get .jar file. can you share me .jar file to try

**Comment by Fritcha** [comment]
I've had the same problem and it seems to fix after reconnecting however i'm not sure why it happens.
My best guess on how to fix it is to increase the delay before sending the join message(I'll edit the comment if i find a way to fix this).
Edit: I changed the delay to 3 ticks instead of 2 and it seems to be working. Try downloading the file in the test branch and if it works for you aswell i'm gonna move it over to main.

**Comment by Nilesh3803** [comment]
can you share me .jar file. i have no access to compile it to .jar

**Comment by Fritcha** [comment]
Its here: https://github.com/Fritcha/Client-Detector/releases/tag/1.1.6

**Comment by Nilesh3803** [comment]
Little bit works. but not 100%

**Comment by Fritcha** [comment]
Ok now im waiting until the client is not null before the message is sent(you can use the last link i sent you for the new file)
Edit: It's been over 50 mins you still there? If not i think ill just release as is.
